export enum FactorName {
  PREGUNTAS_MALAS_PIVOT = 'PREGUNTAS_MALAS_PIVOT',
  FLASHCARDS_MAL_PRIVOT = 'FLASHCARDS_MAL_PRIVOT',
  FLASHCARDS_REPASAR_PIVOT = 'FLASHCARDS_REPASAR_PIVOT',
  FLASHCARDS_BALANCE_NO_RESPONDIDAS = 'FLASHCARDS_BALANCE_NO_RESPONDIDAS',
  FLASHCARDS_BALANCE_MAL = 'FLASHCARDS_BALANCE_MAL',
  FLASHCARDS_BALANCE_REVISAR = 'FLASHCARDS_BALANCE_REVISAR',
  FLASHCARDS_BALANCE_BIEN = 'FLASHCARDS_BALANCE_BIEN',
}
export interface Factor {
  name: FactorName;
  value?: number;
}
